---
- hosts: demo-airbus
  user: ansible
  become: yes
  connection: ssh
  tasks:
  - name: install Java
    yum:
      name:
	-wget
	-java-1.8.0-openjdk

  - name: Download Jenkins Repo
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins key
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install java
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: Start & Enable jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

  - name: Sleep for 30 seconds and continue with play
    wait_for: timeout=30

  - name: Get init password Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result
